language: python

# travis does not support python <= 2.5 https://github.com/travis-ci/travis-ci/issues/8799
matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.4"
      env: TOXENV=py34
    - python: "2.7"
      env: TOXENV=py27
    - python: "2.6"
      env: TOXENV=py26

install:
  - pip install -U tox-travis
  
script:
  - tox
