language: python

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.4"
      env: TOXENV=py34
    - python: "2.7"
      env: TOXENV=py27
    - python: "2.6"
      env: TOXENV=py26
    - python: "2.5"
      env: TOXENV=py25
    - python: "2.4"
      env: TOXENV=py24

install:
  - pip install -U tox-travis
  
script:
  - tox
